name: building containerized OpenWRT Imagebuilder

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo docker builder prune --force --all
      - run: sudo docker system prune --force --all
      - run: sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sudo docker image build --file=Dockerfile --pull --tag=${{ secrets.DOCKERHUB_USERNAME }}/sturdynetoci/docker-openwrt-imagebuilder:22.03.1-latest .
      - run: sudo docker push "${{ secrets.DOCKERHUB_USERNAME }}/sturdynetoci/docker-openwrt-imagebuilder:22.03.1-latest"
      - run: sudo docker logout
